services:
  sql:    
    build:
      context: .
      dockerfile: Dockerfile
    ports:      
      - "1433:1433"    
    volumes:
      - ./db:/var/opt/mssql/data/
      - ./sql-server-scripts:/docker-entrypoint-initdb.d
